// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RdpMonitor.Server.Data;

#nullable disable

namespace RdpMonitor.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("RdpMonitor.Server.Data.AgentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OsVersion")
                        .HasColumnType("TEXT");

                    b.Property<long>("RegisteredAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("RdpMonitor.Server.Data.EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceIp")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("Timestamp");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RdpMonitor.Server.Data.EventTypeSetting", b =>
                {
                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventType");

                    b.ToTable("EventTypeSettings");

                    b.HasData(
                        new
                        {
                            EventType = 0,
                            EmailEnabled = false,
                            Severity = 0
                        },
                        new
                        {
                            EventType = 1,
                            EmailEnabled = true,
                            Severity = 3
                        },
                        new
                        {
                            EventType = 2,
                            EmailEnabled = false,
                            Severity = 0
                        },
                        new
                        {
                            EventType = 3,
                            EmailEnabled = false,
                            Severity = 1
                        },
                        new
                        {
                            EventType = 4,
                            EmailEnabled = false,
                            Severity = 1
                        },
                        new
                        {
                            EventType = 5,
                            EmailEnabled = false,
                            Severity = 0
                        },
                        new
                        {
                            EventType = 6,
                            EmailEnabled = false,
                            Severity = 0
                        },
                        new
                        {
                            EventType = 7,
                            EmailEnabled = false,
                            Severity = 2
                        },
                        new
                        {
                            EventType = 8,
                            EmailEnabled = false,
                            Severity = 0
                        },
                        new
                        {
                            EventType = 9,
                            EmailEnabled = false,
                            Severity = 2
                        },
                        new
                        {
                            EventType = 10,
                            EmailEnabled = false,
                            Severity = 2
                        },
                        new
                        {
                            EventType = 11,
                            EmailEnabled = false,
                            Severity = 3
                        });
                });

            modelBuilder.Entity("RdpMonitor.Server.Data.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("RdpMonitor.Server.Data.EventEntity", b =>
                {
                    b.HasOne("RdpMonitor.Server.Data.AgentEntity", "Agent")
                        .WithMany("Events")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("RdpMonitor.Server.Data.AgentEntity", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
